name: Workflow Events
on: [push,pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger event
        run: echo "I've been triggered by ${{ github.event_name }} event"

